#!/bin/bash

# define some colors to use for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# catch failures and clean up
trap 'printf "${RED}Running redis server interrupted! ${NC}\n"'\
	HUP INT QUIT PIPE TERM

printf "${GREEN}Running redis server${NC}\n"

docker build -t golang-redis-server .

sudo docker run -p 6379:6379/tcp golang-redis-server


