#!/bin/bash

# define some colors to use for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# catch failures and clean up
trap 'printf "${RED}Running redis server interrupted! ${NC}\n"'\
	HUP INT QUIT PIPE TERM

# change to the directory for the main.go file
cd golangredisserver
printf "${GREEN}Running redis server${NC}\n"
go run main.go

